### ISSUE TITLE
CG-30 Maximum Call Stack on King

### ISSUE THREAD

**Issue by TKPending** [TKPending/ChessGame#46]
`movingIntoCheck.js:40 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at enemyPotentialPositions (movingIntoCheck.js:40:33)
    at allEnemyMoves (movingIntoCheck.js:57:33)
    at King.movingIntoCheck (king.js:39:33)
    at King.moveUp (king.js:60:36)
    at King.generateLegalMoves (king.js:188:18)
    at getEnemyMoves (movingIntoCheck.js:30:38)
    at enemyPotentialPositions (movingIntoCheck.js:53:12)
    at allEnemyMoves (movingIntoCheck.js:57:33)
    at King.movingIntoCheck (king.js:39:33)
    at King.moveUp (king.js:60:36)
    `
There are situations when the king is placed into check, then this function gets called. Not sure what is causing it but need to figure it out and sort it

**Comment by TKPending** [comment]
The error was occurring because of a recursion issue. When generating king movements, a part of checking whether a move is valid. It will get all the pieces valid movements, and a part of doing that is generating the moves for each piece. The recursion occurs here, as when we get to the King piece we generate the moves for the other king. Then that process reoccurs. 

This problem was solved within the refactoring. Solved by after moving the king, we generate that kings movement then store it separately. That way when we're generating moves for the next king moves, will use the separated saved moves.
